abstract class AppConst {
  static const kFavTeam = 'kFavTeam';

  static const kUser = 'kUser';

  static const leaguesList = [
    7,
    552,
    17,
    11,
    72,
    113,
    35,
    25,
    57,
    73,
    649,
    104,
  ];

  static const unLikedLeagues = [7649, 5802, 7337];

  static const matchStatsIdsList = [
    10,
    76,
    3,
    4,
    24,
    8,
    9,
    19,
    2,
    5,
    6,
    13,
    21,
    146,
    147,
    36,
    46,
    80,
    23,
    40,
    12,
    1,
  ];

  static const countiesList = [
    {"id": 44, "name": "Africa", "nameForURL": "africa", "isoCode": null},
    {"id": 76, "name": "Albania", "nameForURL": "albania", "isoCode": "al"},
    {"id": 139, "name": "Algeria", "nameForURL": "algeria", "isoCode": "dz"},
    {"id": 103, "name": "Andorra", "nameForURL": "andorra", "isoCode": "ad"},
    {"id": 136, "name": "Angola", "nameForURL": "angola", "isoCode": "ao"},
    {"id": 10, "name": "Argentina", "nameForURL": "argentina", "isoCode": "ar"},
    {"id": 88, "name": "ATP", "nameForURL": "atp", "isoCode": null},
    {"id": 20, "name": "Austria", "nameForURL": "austria", "isoCode": "at"},
    {
      "id": 77,
      "name": "Azerbaijan",
      "nameForURL": "azerbaijan",
      "isoCode": "az",
    },
    {"id": 104, "name": "Belarus", "nameForURL": "belarus", "isoCode": "by"},
    {
      "id": 121,
      "name": "Uzbekistan",
      "nameForURL": "uzbekistan",
      "isoCode": "uz",
    },
    {"id": 16, "name": "Belgium", "nameForURL": "belgium", "isoCode": "be"},
    {"id": 113, "name": "Bolivia", "nameForURL": "bolivia", "isoCode": "bo"},
    {
      "id": 57,
      "name": "Bosnia & Herzegovina",
      "nameForURL": "bosnia-&-herzegovina",
      "isoCode": "ba",
    },
    {"id": 21, "name": "Brazil", "nameForURL": "brazil", "isoCode": "br"},
    {
      "id": 276,
      "name": "Brunei Darussalam",
      "nameForURL": "brunei-darussalam",
      "isoCode": "bn",
    },
    {"id": 40, "name": "Bulgaria", "nameForURL": "bulgaria", "isoCode": "bg"},
    {"id": 192, "name": "Burundi", "nameForURL": "burundi", "isoCode": "bi"},
    {"id": 66, "name": "Canada", "nameForURL": "canada", "isoCode": "ca"},
    {
      "id": 301,
      "name": "Challenger",
      "nameForURL": "challenger",
      "isoCode": null,
    },
    {"id": 28, "name": "Chile", "nameForURL": "chile", "isoCode": "cl"},
    {"id": 109, "name": "Colombia", "nameForURL": "colombia", "isoCode": "co"},
    {
      "id": 153,
      "name": "Costa Rica",
      "nameForURL": "costa-rica",
      "isoCode": "cr",
    },
    {"id": 38, "name": "Croatia", "nameForURL": "croatia", "isoCode": "hr"},
    {"id": 39, "name": "Cyprus", "nameForURL": "cyprus", "isoCode": "cy"},
    {
      "id": 22,
      "name": "Czech Republic",
      "nameForURL": "czech-republic",
      "isoCode": "cz",
    },
    {"id": 23, "name": "Denmark", "nameForURL": "denmark", "isoCode": "dk"},
    {
      "id": 183,
      "name": "Dominican Republic",
      "nameForURL": "dominican-republic",
      "isoCode": "do",
    },
    {"id": 51, "name": "Ecuador", "nameForURL": "ecuador", "isoCode": "ec"},
    {"id": 131, "name": "Egypt", "nameForURL": "egypt", "isoCode": "eg"},
    {
      "id": 147,
      "name": "El Salvador",
      "nameForURL": "el-salvador",
      "isoCode": "sv",
    },
    {"id": 1, "name": "England", "nameForURL": "england", "isoCode": "gb-eng"},
    {
      "id": 8,
      "name": "Scotland",
      "nameForURL": "scotland",
      "isoCode": "gb-sct",
    },
    {"id": 19, "name": "Europe", "nameForURL": "europe", "isoCode": null},
    {"id": 25, "name": "Finland", "nameForURL": "finland", "isoCode": "fi"},
    {"id": 5, "name": "France", "nameForURL": "france", "isoCode": "fr"},
    {"id": 4, "name": "Germany", "nameForURL": "germany", "isoCode": "de"},
    {"id": 65, "name": "Ghana", "nameForURL": "ghana", "isoCode": "gh"},
    {
      "id": 209,
      "name": "Gibraltar",
      "nameForURL": "gibraltar",
      "isoCode": "gi",
    },
    {"id": 13, "name": "Greece", "nameForURL": "greece", "isoCode": "gr"},
    {
      "id": 140,
      "name": "Guatemala",
      "nameForURL": "guatemala",
      "isoCode": "gt",
    },
    {"id": 169, "name": "Honduras", "nameForURL": "honduras", "isoCode": "hn"},
    {"id": 30, "name": "Hungary", "nameForURL": "hungary", "isoCode": "hu"},
    {"id": 32, "name": "Iceland", "nameForURL": "iceland", "isoCode": "is"},
    {
      "id": 54,
      "name": "International",
      "nameForURL": "international",
      "isoCode": null,
    },
    {"id": 114, "name": "Iraq", "nameForURL": "iraq", "isoCode": "iq"},
    {"id": 6, "name": "Israel", "nameForURL": "israel", "isoCode": "il"},
    {"id": 3, "name": "Italy", "nameForURL": "italy", "isoCode": "it"},
    {
      "id": 74,
      "name": "Ivory Coast",
      "nameForURL": "ivory-coast",
      "isoCode": "ci",
    },
    {
      "id": 105,
      "name": "Kazakhstan",
      "nameForURL": "kazakhstan",
      "isoCode": "kz",
    },
    {"id": 41, "name": "Latvia", "nameForURL": "latvia", "isoCode": "lv"},
    {"id": 42, "name": "Lithuania", "nameForURL": "lithuania", "isoCode": "lt"},
    {
      "id": 92,
      "name": "Luxembourg",
      "nameForURL": "luxembourg",
      "isoCode": "lu",
    },
    {"id": 93, "name": "Malta", "nameForURL": "malta", "isoCode": "mt"},
    {"id": 31, "name": "Mexico", "nameForURL": "mexico", "isoCode": "mx"},
    {"id": 91, "name": "Moldova", "nameForURL": "moldova", "isoCode": "md"},
    {
      "id": 84,
      "name": "Montenegro",
      "nameForURL": "montenegro",
      "isoCode": "me",
    },
    {"id": 127, "name": "Morocco", "nameForURL": "morocco", "isoCode": "ma"},
    {
      "id": 7,
      "name": "Netherlands",
      "nameForURL": "netherlands",
      "isoCode": "nl",
    },
    {
      "id": 182,
      "name": "Nicaragua",
      "nameForURL": "nicaragua",
      "isoCode": "ni",
    },
    {"id": 83, "name": "Nigeria", "nameForURL": "nigeria", "isoCode": "ng"},
    {"id": 27, "name": "Norway", "nameForURL": "norway", "isoCode": "no"},
    {"id": 146, "name": "Panama", "nameForURL": "panama", "isoCode": "pa"},
    {"id": 108, "name": "Paraguay", "nameForURL": "paraguay", "isoCode": "py"},
    {"id": 112, "name": "Peru", "nameForURL": "peru", "isoCode": "pe"},
    {"id": 37, "name": "Poland", "nameForURL": "poland", "isoCode": "pl"},
    {"id": 11, "name": "Portugal", "nameForURL": "portugal", "isoCode": "pt"},
    {
      "id": 178,
      "name": "Puerto Rico",
      "nameForURL": "puerto-rico",
      "isoCode": "pr",
    },
    {"id": 115, "name": "Qatar", "nameForURL": "qatar", "isoCode": "qa"},
    {"id": 29, "name": "Romania", "nameForURL": "romania", "isoCode": "ro"},
    {"id": 14, "name": "Russia", "nameForURL": "russia", "isoCode": "ru"},
    {
      "id": 94,
      "name": "San Marino",
      "nameForURL": "san-marino",
      "isoCode": "sm",
    },
    {
      "id": 122,
      "name": "Saudi Arabia",
      "nameForURL": "saudi-arabia",
      "isoCode": "sa",
    },
    {"id": 133, "name": "Senegal", "nameForURL": "senegal", "isoCode": "sn"},
    {"id": 85, "name": "Serbia", "nameForURL": "serbia", "isoCode": "rs"},
    {"id": 33, "name": "Slovakia", "nameForURL": "slovakia", "isoCode": "sk"},
    {"id": 46, "name": "Slovenia", "nameForURL": "slovenia", "isoCode": "si"},
    {
      "id": 134,
      "name": "South Africa",
      "nameForURL": "south-africa",
      "isoCode": "za",
    },
    {"id": 2, "name": "Spain", "nameForURL": "spain", "isoCode": "es"},
    {"id": 24, "name": "Sweden", "nameForURL": "sweden", "isoCode": "se"},
    {
      "id": 15,
      "name": "Switzerland",
      "nameForURL": "switzerland",
      "isoCode": "ch",
    },
    {"id": 141, "name": "Tanzania", "nameForURL": "tanzania", "isoCode": "tz"},
    {"id": 71, "name": "Togo", "nameForURL": "togo", "isoCode": "tg"},
    {"id": 135, "name": "Tunisia", "nameForURL": "tunisia", "isoCode": "tn"},
    {"id": 12, "name": "Turkiye", "nameForURL": "turkiye", "isoCode": "tr"},
    {"id": 124, "name": "UAE", "nameForURL": "uae", "isoCode": "ae"},
    {"id": 26, "name": "Ukraine", "nameForURL": "ukraine", "isoCode": "ua"},
    {
      "id": 166,
      "name": "United Kingdom",
      "nameForURL": "united-kingdom",
      "isoCode": "gb",
    },
    {"id": 111, "name": "Uruguay", "nameForURL": "uruguay", "isoCode": "uy"},
    {"id": 18, "name": "USA", "nameForURL": "usa", "isoCode": "us"},
    {
      "id": 110,
      "name": "Venezuela",
      "nameForURL": "venezuela",
      "isoCode": "ve",
    },
    {"id": 155, "name": "Vietnam", "nameForURL": "vietnam", "isoCode": "vn"},
    {"id": 302, "name": "WTA 125K", "nameForURL": "wta-125k", "isoCode": null},
    {"id": 132, "name": "Zambia", "nameForURL": "zambia", "isoCode": "zm"},
    {"id": 60, "name": "Zimbabwe", "nameForURL": "zimbabwe", "isoCode": "zw"},
  ];
}
