abstract class AppConst {
  static const kFavTeam = 'kFavTeam';

  static const leaguesList = [
    7,
    552,
    17,
    11,
    72,
    113,
    35,
    25,
    57,
    73,
    649,
    104,
  ];

  static const unLikedLeagues = [7649, 5802, 7337];

  static const matchStatsIdsList = [
    10,
    76,
    3,
    4,
    24,
    8,
    9,
    19,
    2,
    5,
    6,
    13,
    21,
    146,
    147,
    36,
    46,
    80,
    23,
    40,
    12,
    1,
  ];

  static const countiesList = [
    {"id": 44, "name": "Africa", "nameForURL": "africa"},
    {"id": 76, "name": "Albania", "nameForURL": "albania"},
    {"id": 139, "name": "Algeria", "nameForURL": "algeria"},
    {"id": 103, "name": "Andorra", "nameForURL": "andorra"},
    {"id": 136, "name": "Angola", "nameForURL": "angola"},
    {"id": 10, "name": "Argentina", "nameForURL": "argentina"},
    {"id": 88, "name": "ATP", "nameForURL": "atp"},
    {"id": 20, "name": "Austria", "nameForURL": "austria"},
    {"id": 77, "name": "Azerbaijan", "nameForURL": "azerbaijan"},
    {"id": 104, "name": "Belarus", "nameForURL": "belarus"},
    {"id": 121, "name": "Uzbekistan", "nameForURL": "uzbekistan"},
    {"id": 16, "name": "Belgium", "nameForURL": "belgium"},
    {"id": 113, "name": "Bolivia", "nameForURL": "bolivia"},
    {
      "id": 57,
      "name": "Bosnia & Herzegovina",
      "nameForURL": "bosnia-&-herzegovina",
    },
    {"id": 21, "name": "Brazil", "nameForURL": "brazil"},
    {"id": 276, "name": "Brunei Darussalam", "nameForURL": "brunei-darussalam"},
    {"id": 40, "name": "Bulgaria", "nameForURL": "bulgaria"},
    {"id": 192, "name": "Burundi", "nameForURL": "burundi"},
    {"id": 66, "name": "Canada", "nameForURL": "canada"},
    {"id": 301, "name": "Challenger", "nameForURL": "challenger"},
    {"id": 28, "name": "Chile", "nameForURL": "chile"},
    {"id": 109, "name": "Colombia", "nameForURL": "colombia"},
    {"id": 153, "name": "Costa Rica", "nameForURL": "costa-rica"},
    {"id": 38, "name": "Croatia", "nameForURL": "croatia"},
    {"id": 39, "name": "Cyprus", "nameForURL": "cyprus"},
    {"id": 22, "name": "Czech Republic", "nameForURL": "czech-republic"},
    {"id": 23, "name": "Denmark", "nameForURL": "denmark"},
    {
      "id": 183,
      "name": "Dominican Republic",
      "nameForURL": "dominican-republic",
    },
    {"id": 51, "name": "Ecuador", "nameForURL": "ecuador"},
    {"id": 131, "name": "Egypt", "nameForURL": "egypt"},
    {"id": 147, "name": "El Salvador", "nameForURL": "el-salvador"},
    {"id": 1, "name": "England", "nameForURL": "england"},
    {"id": 19, "name": "Europe", "nameForURL": "europe"},
    {"id": 25, "name": "Finland", "nameForURL": "finland"},
    {"id": 5, "name": "France", "nameForURL": "france"},
    {"id": 4, "name": "Germany", "nameForURL": "germany"},
    {"id": 65, "name": "Ghana", "nameForURL": "ghana"},
    {"id": 209, "name": "Gibraltar", "nameForURL": "gibraltar"},
    {"id": 13, "name": "Greece", "nameForURL": "greece"},
    {"id": 140, "name": "Guatemala", "nameForURL": "guatemala"},
    {"id": 169, "name": "Honduras", "nameForURL": "honduras"},
    {"id": 30, "name": "Hungary", "nameForURL": "hungary"},
    {"id": 32, "name": "Iceland", "nameForURL": "iceland"},
    {"id": 54, "name": "International", "nameForURL": "international"},
    {"id": 114, "name": "Iraq", "nameForURL": "iraq"},
    {"id": 6, "name": "Israel", "nameForURL": "israel"},
    {"id": 3, "name": "Italy", "nameForURL": "italy"},
    {"id": 74, "name": "Ivory Coast", "nameForURL": "ivory-coast"},
    {"id": 105, "name": "Kazakhstan", "nameForURL": "kazakhstan"},
    {"id": 41, "name": "Latvia", "nameForURL": "latvia"},
    {"id": 42, "name": "Lithuania", "nameForURL": "lithuania"},
    {"id": 92, "name": "Luxembourg", "nameForURL": "luxembourg"},
    {"id": 93, "name": "Malta", "nameForURL": "malta"},
    {"id": 31, "name": "Mexico", "nameForURL": "mexico"},
    {"id": 91, "name": "Moldova", "nameForURL": "moldova"},
    {"id": 84, "name": "Montenegro", "nameForURL": "montenegro"},
    {"id": 127, "name": "Morocco", "nameForURL": "morocco"},
    {"id": 7, "name": "Netherlands", "nameForURL": "netherlands"},
    {"id": 182, "name": "Nicaragua", "nameForURL": "nicaragua"},
    {"id": 83, "name": "Nigeria", "nameForURL": "nigeria"},
    {"id": 27, "name": "Norway", "nameForURL": "norway"},
    {"id": 146, "name": "Panama", "nameForURL": "panama"},
    {"id": 108, "name": "Paraguay", "nameForURL": "paraguay"},
    {"id": 112, "name": "Peru", "nameForURL": "peru"},
    {"id": 37, "name": "Poland", "nameForURL": "poland"},
    {"id": 11, "name": "Portugal", "nameForURL": "portugal"},
    {"id": 178, "name": "Puerto Rico", "nameForURL": "puerto-rico"},
    {"id": 115, "name": "Qatar", "nameForURL": "qatar"},
    {"id": 29, "name": "Romania", "nameForURL": "romania"},
    {"id": 14, "name": "Russia", "nameForURL": "russia"},
    {"id": 94, "name": "San Marino", "nameForURL": "san-marino"},
    {"id": 122, "name": "Saudi Arabia", "nameForURL": "saudi-arabia"},
    {"id": 8, "name": "Scotland", "nameForURL": "scotland"},
    {"id": 133, "name": "Senegal", "nameForURL": "senegal"},
    {"id": 85, "name": "Serbia", "nameForURL": "serbia"},
    {"id": 33, "name": "Slovakia", "nameForURL": "slovakia"},
    {"id": 46, "name": "Slovenia", "nameForURL": "slovenia"},
    {"id": 134, "name": "South Africa", "nameForURL": "south-africa"},
    {"id": 2, "name": "Spain", "nameForURL": "spain"},
    {"id": 24, "name": "Sweden", "nameForURL": "sweden"},
    {"id": 15, "name": "Switzerland", "nameForURL": "switzerland"},
    {"id": 141, "name": "Tanzania", "nameForURL": "tanzania"},
    {"id": 71, "name": "Togo", "nameForURL": "togo"},
    {"id": 135, "name": "Tunisia", "nameForURL": "tunisia"},
    {"id": 12, "name": "Turkiye", "nameForURL": "turkiye"},
    {"id": 124, "name": "UAE", "nameForURL": "uae"},
    {"id": 26, "name": "Ukraine", "nameForURL": "ukraine"},
    {"id": 166, "name": "United Kingdom", "nameForURL": "united-kingdom"},
    {"id": 111, "name": "Uruguay", "nameForURL": "uruguay"},
    {"id": 18, "name": "USA", "nameForURL": "usa"},
    {"id": 110, "name": "Venezuela", "nameForURL": "venezuela"},
    {"id": 155, "name": "Vietnam", "nameForURL": "vietnam"},
    {"id": 302, "name": "WTA 125K", "nameForURL": "wta-125k"},
    {"id": 132, "name": "Zambia", "nameForURL": "zambia"},
    {"id": 60, "name": "Zimbabwe", "nameForURL": "zimbabwe"},
  ];
}
